General:
    seed: 2022
    gpus: cuda
    epochs: &epoch 200 
    accumulation_steps: 1
    num_epochs: 200
    lr: 0.0002
    server: train #train #test
     
    
    
Data:
    dataset_name: Brast2020
    data_shuffle: False
    root: brats20-dataset-training-validation/
    train_path: BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData/
    val_path: BraTS2020_ValidationData/MICCAI_BraTS2020_ValidationData/
    name_mapping_path: name_mapping.csv
    survival_info_path: survival_info.csv
    path_to_csv: train_df.csv
    fold: 0
    nfold: 4

    train_dataloader:
        batch_size: 1 
        num_workers: 0

    test_dataloader:
        batch_size: 1
        num_workers: 0

Model:
    name: AttentionUNetPlus
    n_classes: 3



Loss:
    base_loss: BCEDiceLoss


